### ISSUE TITLE
Add a comment regarding middleware ordering

### ISSUE THREAD

**Issue by Abrissirba** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#11]
This is not any issue with your code really but more a help for others that, like me, didn't  fully understood how the new middleware arhitecture works. I added `app.UseJwtBearerAuthentication` after `app.useMvc()` which resulted in an error saying that I had no authentication handler for Bearer. It took a while before I realised that, of course, the order of middlewares matters. So a comment in the code saying that `app.UseJwtBearerAuthentication` needs to come before `asp.useMvc()` could be helpful for others :)

**Comment by mrsheepuk** [comment]
That's a great point, I'll add that in shortly! Thanks for pointing it out.

**Comment by mrsheepuk** [comment]
Comment added.
