### ISSUE TITLE
TokenController

### ISSUE THREAD

**Issue by cowsgoo** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#14]
I've been trying to get this sample to work. When/how is TokenController supposed to be called?

**Comment by mrsheepuk** [comment]
It should be called by your consuming application to retrieve a token @cowsgoo

**Comment by cowsgoo** [comment]
Do you currently call it anywhere? When I try doing a get on /api/values/5 for example it doesn't seem to get called?

**Comment by cowsgoo** [comment]
Thanks!
