### ISSUE TITLE
Integrating with ASP Core Identity..

### ISSUE THREAD

**Issue by mikecann** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#16]
Hi,

First thanks for such a great sample, you have no idea how long I have spent banging my head against this.

After getting this sample working I decided I want to try to integrate it into the standard ASP Core RC2 sample that comes with the latest Visual Studio. 

I took your code and wove it in and to my great surprise it worked!

Now im trying to get it to work with the SQL DB that comes with the sample template. I have modified the TokenController Post function to look like this:

```
[HttpPost]
public async Task<dynamic> Post(string email, string password)
{
    var result = await _signInManager.PasswordSignInAsync(email, password, false, false);
    if (result.Succeeded)
    {
        DateTime? expires = DateTime.UtcNow.AddMinutes(2);
        var token = GetToken(email, expires);
        return new { authenticated = true, entityId = 1, token = token, tokenExpires = expires };
    }

    return new { authenticated = false };
}
```

And that works well. Now I notice that in GetToken() you mention:

```
// Here, you should create or look up an identity for the user which is being authenticated.
// For now, just creating a simple generic identity.
var identity = new ClaimsIdentity(new GenericIdentity(user, "TokenAuth"), new[] { new Claim("EntityID", "1", ClaimValueTypes.Integer) });
```

Could you please explain a little about ClaimsIdentity, and Claims and how I should intergrate that with the ASP UserManager / SignInManager?

Thanks so much,
Mike

**Comment by mrsheepuk** [comment]
Hi  @mikecann - the identity created here is encoded into the JWT token which will be returned to the user, in effect it encapsulates all of the details of that user that you'll need to use to assess whether that user is authorised to perform an action when they make future calls to the API and present that JWT token as the authorisation header.

If you take a look in the Startup.cs, you can see that we're [simply requiring that a user has a valid token in this example](https://github.com/mrsheepuk/ASPNETSelfCreatedTokenAuthExample/blob/master/src/TokenAuthExampleWebApplication/Startup.cs#L54), however you can build up arbitrarily complex authorisation rules using the claims data you include in this identity. So for example, you could have a "Company" claim with a value of the company a user is an employee of, say "Monkey Company Plc". You could then create a policy to check if the user attempted to access an API end point to retrieve details about a company, that they were an employee of the company in question.

What Claims you create, and what meanings you ascribe to them, are completely up to your application's needs. As to whether you can derive them from the UserManager / SignInManager, I'm not sure - I've not used ASP.Net Core Identity, but looking at [the code for the UserManager in ASP.Net Core](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs) it looks like it has all sorts of stuff to do with Claims going on there, so it seems like it should be able to directly support the management of the claims and generating relevant claims identity objects to be inserted into your tokens here.

**Comment by mikecann** [comment]
Hi @mrsheepuk,

Thanks for that detailed info! Really helpful. 

I was wondering, you add [Authorize("Bearer")] to methods you want protected. Its not a big issue but setting [Authorize] doesnt seem to work. Is there a way to make it generic?

Cheers,
Mike

**Comment by mrsheepuk** [comment]
@mikecann There almost certainly is, yes - take a look at the line in the startup.cs:

    services.AddAuthorization(auth =>
    {
        auth.AddPolicy("Bearer", new AuthorizationPolicyBuilder()
            .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme‌​)
            .RequireAuthenticatedUser().Build());
    });

Changing this to something like:

    services.AddAuthorization(auth =>
    {
        auth.DefaultPolicy = new AuthorizationPolicyBuilder()
            .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme‌​)
            .RequireAuthenticatedUser().Build();
    });

... Should fix it (I haven't tested this, mind).
