### ISSUE TITLE
netcoreapp 1.0

### ISSUE THREAD

**Issue by zhouhao27** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#18]
.Net Core is released. I'm wondering if this project can be upgraded into netcoreapp1.0 framework instead of using dnx?

**Comment by houseOfEorl** [comment]
I did a few changes on this project to upgrade it to netcoreapp1.0, I have published it in the repo below, but maybe we can create a new branch here.

https://github.com/houseOfEorl/AspNetCoreSelfCreatedTokenAuthExample

**Comment by mrsheepuk** [comment]
I've updated the code to netcoreapp 1.0. Please have a look and comment here if you find any problems.
