### ISSUE TITLE
Update to core 1.1

### ISSUE THREAD

**Issue by Vitormdias** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#22]

**Comment by mockpit** [comment]
@Vitormdias I'm currently using this sample with core 1.1, is there a gotcha somewhere that hasn't bit me yet?

**Comment by houseOfEorl** [comment]
I'm using it with core 1.1 as well

**Comment by Vitormdias** [comment]
No, I thought it would, so I opened the issue
