### ISSUE TITLE
Sliding expiration for token

### ISSUE THREAD

**Issue by sudarshanb** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#4]
Hi,

Thank you for excellent demo application! This is really a time saver
Looks like current sample has fixed token expiration time. Is there any way to have this as sliding expiration?

Thank you

**Comment by mrsheepuk** [comment]
Not directly (sliding windows aren't part of JWT tokens), but you can use the current token to retrieve a new one (this may be a bad idea though, see below):

https://github.com/mrsheepuk/ASPNETSelfCreatedTokenAuthExample/blob/master/src/TokenAuthExampleWebApplication/Controllers/TokenController.cs#L33

So in our case here, if you perform a GET against /api/token, you'll get a new token back in the response, which you can then use for future requests. On your client side, you'd need to set up some sort of timer or similar to request new tokens before the old ones expire, based on whatever criteria you wish for detecting if the user is still "active".

It's not quite the same as sliding expiration, but it's as close as you can get simply. 

**However** all that said, it's probably not a good idea to use this in production as essentially it means that with a token, someone can remain logged in forever and there's nothing that can be done to ever remove their access, even if the user's password is changed. What should be used is a "refresh token" as described here - https://auth0.com/docs/refresh-token - which can be revoked if the user logs out or similar. That refresh token should then be used to retrieve new tokens.

**Comment by mrsheepuk** [comment]
Raised issue #5 to close this security hole and provide a "correct" way of refreshing tokens. Closing this issue as it's not possible to do true sliding windows with JWT tokens.

Thanks for raising this though as it's highlighted an important security hole in this example!
