### ISSUE TITLE
Authorize Roles

### ISSUE THREAD

**Issue by originalmoose** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#7]
Is it possible to use this method to authorize a route based on the users role? I was able to put the roles into the claims just fine but when I attempt to add the Authorize attribute with the roles property set I get an unauthorized result back.

**Comment by mrsheepuk** [comment]
That should work - I've only used policy-based authorisation myself (which
seems to be the more recommended way of doing things for AST.NET 5 / MVC
6), but I don't know of any reason why roles-based authorisation would be a
problem.

**Comment by mrsheepuk** [comment]
@originalmoose did you sort this out? It sounds to me like you've confused claims and roles - they're not the same thing, I don't believe, so putting the roles into claims isn't the right thing to do. If the principal that you use to generate the token has the roles associated with it, it should probably "just work" - although as I say I haven't tested it.

The [docs on this](https://docs.asp.net/en/latest/security/authorization/index.html) are pretty good - worth having a read if you're still having trouble.

Closing as this isn't really an issue with the token auth strategy, more a question about roles/claims authorisation in ASP.NET 5. Please re-open if there's something specific to the token-based auth that is causing trouble!
