### ISSUE TITLE
HMAC-SHA signing with secret

### ISSUE THREAD

**Issue by bragma** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#8]
Hi,
thanks again for this excellent demo. I am trying to reduce the size of generated JWT tokens. At the moment, signature is more than 3 times the size of the payload. I think using HMACSHA256 signature with secret key could reduce the global token size.
I've tried to use it instead of RSA, but failed. Could you please improve your demo with this signing method? Thanks a lot!

**Comment by mrsheepuk** [comment]
I don't have the need for this myself, but if you can work out how to do it as an optional feature I'd be happy to receive a pull request to add that functionality in to this demo.
